/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "./Layout";
import MainContent from "./page";

const App: React.FC = () => {
  return (
    <Layout>
      <MainContent>{/* Add any additional content here */}</MainContent>
    </Layout>
  );
};

export default App;
