/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";
import FilterButton from "./FilterButton";
import ViewToggle from "./ViewToggle";
import TaskList from "./TaskList";

interface MainContentProps {
  children: React.ReactNode;
}

const MainContent: React.FC<MainContentProps> = ({ children }) => {
  return (
    <main className="flex flex-col ml-5 w-[78%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col self-stretch my-auto w-full max-md:mt-10 max-md:max-w-full">
        <h2 className="self-start text-xl font-semibold tracking-normal text-black">
          Announcements
        </h2>
        <div className="flex flex-wrap gap-5 justify-between mt-4 w-full max-md:max-w-full">
          <div className="flex flex-wrap gap-4 text-base text-zinc-500 max-md:max-w-full">
            <SearchBar />
            <FilterButton />
          </div>
          <ViewToggle />
        </div>
        <TaskList />
        <button className="gap-2 self-end px-4 mt-20 mr-12 text-base font-medium text-white whitespace-nowrap bg-teal-500 rounded-lg min-h-[40px] shadow-[0px_4px_4px_rgba(0,0,0,0.25)] max-md:mt-10 max-md:mr-2.5">
          Next
        </button>
      </div>
      {children}
    </main>
  );
};

export default MainContent;
