/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SidebarItem from "./SidebarItem";
import SidebarSection from "./SidebarSection";

const Sidebar: React.FC = () => {
  return (
    <aside className="flex flex-col w-[22%] max-md:ml-0 max-md:w-full">
      <nav className="flex overflow-hidden flex-col grow w-full text-base font-semibold text-white bg-white border-r border-neutral-200 max-md:mt-5">
        <div className="flex overflow-hidden flex-col bg-white border-r border-neutral-200">
          <div className="flex flex-col items-start pt-7 pr-1.5 pb-24 w-full bg-slate-900 rounded-[76px]">
            <SidebarItem label="Home" active />
            <SidebarItem label="Home" />
            <h1 className="z-10 -mt-6 ml-4 text-3xl tracking-tight text-zinc-100 max-md:ml-2.5">
              Skill³
            </h1>
            <div className="flex flex-col self-stretch mt-14 w-full text-xl font-medium max-md:mt-10">
              <div className="flex flex-col items-start pr-12 pl-5 w-full font-semibold whitespace-nowrap max-md:pr-5">
                <SidebarItem
                  label="Home"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/38e390ce89f8e7dee0a956423d9453ef22c54a7f0a798bfe0d34eaf7400fbeca?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                />
                <SidebarItem
                  label="Dashboard"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/38e390ce89f8e7dee0a956423d9453ef22c54a7f0a798bfe0d34eaf7400fbeca?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                />
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/65202168aab88bd2cf4b3af333e951f187227c9112e2247883e1fce288a30599?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-5 w-full max-md:mr-1.5"
              />
              <SidebarSection title="ACADEMIC">
                <SidebarItem
                  label="New Skill"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/3e7300c292f33840d4c99447b988a163c5f41b3da9b2ab99d77ebfac0bd0c176?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                />
                <SidebarItem
                  label="Expert"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/5d93f1870cba39b4ca9b1fc93f26f1496c0ff6e65adcd91a3f7e8c43a347c98f?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                />
                <SidebarItem
                  label="Progress"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/1596e17ce4fcfd316d0963ba95688430d5c9e8231cb9c91fd9d8ad443b625bf9?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                />
                <SidebarItem
                  label="Chat"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/a7cd00136ab49eb27b6a34400c7f07518d724d739152da8940d28d4947c0deee?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                />
                <SidebarItem
                  label="Announcements"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/e80876020e9436de55a94cf3963c777d3eacd8d5247cc96800ba1cfeb8cf20ea?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                />
              </SidebarSection>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/8079025b46cd1b9dfeb24fbd326b42c400a6d7451fde99f64b29efbe285fe46e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-1.5 w-full aspect-[250]"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/82a6eb4b486b708b34f6a447b8d0ce8a768261f2d9881380e1424491516f0011?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain self-start mt-36 w-full aspect-[250] max-md:mt-10"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/72bee63fa8fd87abb25256e4f3077a34a8b9dc39da988e0bc5a1c7b6b353dbb3?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-3.5 w-full aspect-[250]"
              />
              <SidebarSection title="SETTINGS">
                <SidebarItem
                  label="Account settings"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/d74bc400082c2bf6c73c51c40e6083259988fa242b94f777557be2bcb35ccebe?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                />
                <SidebarItem
                  label="Notification preferences"
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/fcf282d08d3d0370f08e64a61f6c0eadbb6012d475ec1a129249efe8ead4e3e5?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                />
              </SidebarSection>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/806a62aeab22292b8114173ff0bb3945f7808ce63a80aedcc06ae9b5dc5a97c2?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain self-start mt-6 w-full aspect-[250]"
              />
              <SidebarItem
                label="Logout"
                icon="https://cdn.builder.io/api/v1/image/assets/TEMP/861ad2da8afd25c5039f7d443fbd5c41155f868df111d013dfc1ec43f104e2c2?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              />
            </div>
          </div>
        </div>
      </nav>
    </aside>
  );
};

export default Sidebar;
