/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface MenuItemProps {
  text: string;
  src: string;
}

const MenuItem: React.FC<MenuItemProps> = ({ text, src }) => (
  <div className="flex gap-2.5 px-3.5 py-2.5 rounded-md border-white border-l-[5px]">
    <img
      loading="lazy"
      src={src}
      alt=""
      className="object-contain shrink-0 my-auto w-5 aspect-square"
    />
    <div className="flex-1 shrink">{text}</div>
  </div>
);

const Sidebar: React.FC = () => (
  <aside className="flex flex-col items-start pt-7 pr-1.5 pb-48 w-full bg-slate-900 rounded-[76px] max-md:pb-24">
    <div className="flex-1 shrink gap-2.5 px-3.5 py-2.5 whitespace-nowrap rounded-md border-white border-l-[5px]">
      Home
    </div>
    <div className="z-10 flex-1 shrink gap-2.5 px-3.5 py-2.5 mt-0 whitespace-nowrap rounded-md border-white border-l-[5px]">
      Home
    </div>
    <div className="z-10 -mt-6 ml-4 text-3xl tracking-tight text-zinc-100 max-md:ml-2.5">
      Skill³
    </div>
    <nav className="flex flex-col self-stretch mt-14 mb-0 w-full text-xl font-medium max-md:mt-10 max-md:mb-2.5">
      <ul className="flex flex-col items-start pr-12 pl-5 w-full font-semibold whitespace-nowrap max-md:pr-5">
        <li>
          <MenuItem
            text="Home"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/2a950554c8471f0356d2f3758e5f317b108e62a5c48b37e56189acd83058412a?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          />
        </li>
        <li className="mt-3.5">
          <MenuItem
            text="Dashboard"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/d67412d0bc484559ac6ba6c8ecb057d920e1278aeeb5def34c91c60e7df5f7f8?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          />
        </li>
      </ul>
    </nav>
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/65202168aab88bd2cf4b3af333e951f187227c9112e2247883e1fce288a30599?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
      alt=""
      className="object-contain mt-5 w-full max-md:mr-1.5"
    />
    <section className="flex flex-col items-start px-5 mt-7 w-full max-md:pr-5">
      <h2>ACADEMIC</h2>
      <ul>
        <li>
          <MenuItem
            text="New Skill"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b7b413fbce2cb4bca6ff5d17f6de0ada0613f2838cc4888395f2f656fdb14023?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          />
        </li>
        <li className="mt-3">
          <MenuItem
            text="Expert"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/dd1a5b6a4cf0082102feba60a161e5d18e78f4c316929856a6b09594bf5ccb18?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          />
        </li>
        <li className="mt-2.5 text-teal-500">
          <MenuItem
            text="Progress"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/7b367ff07cc0fbdba127cd4b718c475f1046280ed94a343a7de25b3205751ef6?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          />
        </li>
        <li className="mt-2.5">
          <MenuItem
            text="Chat"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/8401fd6dcd02a11b32d9cb7f6ec30305a0b5e1fbcdf3307634ca82f8b7a0b42e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          />
        </li>
        <li className="mt-2.5">
          <MenuItem
            text="Announcements"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/3275b57f34ef31ccc87d3808a0a893fa187cea05ab0bfd024b1742b4370bb2c8?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          />
        </li>
      </ul>
    </section>
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/8079025b46cd1b9dfeb24fbd326b42c400a6d7451fde99f64b29efbe285fe46e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
      alt=""
      className="object-contain mt-1.5 w-full aspect-[250]"
    />
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/82a6eb4b486b708b34f6a447b8d0ce8a768261f2d9881380e1424491516f0011?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
      alt=""
      className="object-contain self-start mt-36 w-full aspect-[250] max-md:mt-10"
    />
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/72bee63fa8fd87abb25256e4f3077a34a8b9dc39da988e0bc5a1c7b6b353dbb3?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
      alt=""
      className="object-contain mt-3.5 w-full aspect-[250]"
    />
    <section className="flex flex-col items-start pr-9 pl-2.5 mt-1.5 w-full text-base max-md:pr-5">
      <h2 className="ml-3 text-base max-md:ml-2.5">SETTINGS</h2>
      <ul>
        <li>
          <MenuItem
            text="Account settings"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/00f7fbad29da18e90e63db389c351ba92eaf9d5d951c0cf95fa6d168fc6e03b0?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          />
        </li>
        <li className="mt-2.5 py-2.5 pl-3.5 min-h-[40px]">
          <MenuItem
            text="Notification preferences"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/c81bfd5c426f5f9df81d53540103e467f0e70e0682aaa5504c3e3c9ed2423b8f?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          />
        </li>
      </ul>
    </section>
    <img
      loading="lazy"
      src="https://cdn.builder.io/api/v1/image/assets/TEMP/806a62aeab22292b8114173ff0bb3945f7808ce63a80aedcc06ae9b5dc5a97c2?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
      alt=""
      className="object-contain self-start mt-6 w-full aspect-[250]"
    />
    <div className="flex overflow-hidden gap-2.5 self-start px-3.5 py-2.5 mt-4 text-base whitespace-nowrap min-h-[39px] max-md:ml-2.5">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/a2ecddb5b70c3af11c57c23708dab7ed6d843cae957d703b0bdf24d4b4781373?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
        alt=""
        className="object-contain shrink-0 my-auto w-5 aspect-square"
      />
      <div className="flex-1 shrink">Logout</div>
    </div>
  </aside>
);

export default Sidebar;
