/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface TableProps {
  rows: Array<Array<string>>;
}

const Table: React.FC<TableProps> = ({ rows }) => (
  <div className="flex items-start self-start mt-14 text-sm leading-none text-slate-500 max-md:mt-10">
    <div className="flex flex-col min-w-[240px] w-[422px] max-md:max-w-full">
      <div className="self-stretch px-6 py-3 w-full text-xs font-medium tracking-wide leading-none uppercase bg-gray-50 max-md:px-5 max-md:max-w-full">
        Wallet address
      </div>
      <div className="flex w-full bg-zinc-200 min-h-[1px] max-md:max-w-full" />
      {rows.map((row, index) => (
        <div
          key={index}
          className={`self-stretch px-6 py-4 w-full ${
            index % 2 === 1 ? "bg-gray-50" : ""
          } whitespace-nowrap max-md:px-5 max-md:max-w-full`}
        >
          {row[0]}
        </div>
      ))}
    </div>
    <div className="flex flex-col font-medium text-neutral-800 w-[183px]">
      <div className="self-stretch px-6 py-3 w-full text-xs tracking-wide leading-none uppercase whitespace-nowrap bg-gray-50 text-slate-500 max-md:px-5">
        Date
      </div>
      <div className="flex w-full bg-zinc-200 min-h-[1px]" />
      {rows.map((row, index) => (
        <div
          key={index}
          className={`self-stretch py-4 pr-5 pl-6 w-full ${
            index % 2 === 1 ? "bg-gray-50" : ""
          } max-md:pl-5`}
        >
          {row[1]}
        </div>
      ))}
    </div>
    <div className="flex flex-col min-w-[240px] w-[268px]">
      <div className="self-stretch px-6 py-3 w-full text-xs font-medium tracking-wide leading-none uppercase bg-gray-50 max-md:px-5">
        EVENT
      </div>
      <div className="flex w-full bg-zinc-200 min-h-[1px]" />
      {rows.map((row, index) => (
        <div
          key={index}
          className={`self-stretch px-6 py-4 w-full ${
            index % 2 === 1 ? "bg-gray-50" : ""
          } whitespace-nowrap max-md:px-5`}
        >
          {row[2]}
        </div>
      ))}
    </div>
    <div className="flex flex-col whitespace-nowrap min-w-[240px] w-[275px]">
      <div className="self-stretch px-6 py-3 w-full text-xs font-medium tracking-wide leading-none uppercase bg-gray-50 max-md:px-5">
        Amount
      </div>
      <div className="flex w-full bg-zinc-200 min-h-[1px]" />
      {rows.map((row, index) => (
        <div
          key={index}
          className={`self-stretch px-6 py-4 w-full ${
            index % 2 === 1 ? "bg-gray-50" : ""
          } max-md:px-5`}
        >
          {row[3]}
        </div>
      ))}
    </div>
  </div>
);

export default Table;
