/**
 * This code was generated by Builder.io.
 */
import React from "react";

const AboutSection: React.FC = () => {
  return (
    <section className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col text-sky-500 max-md:mt-7">
        <h2 className="self-start ml-10 text-sm font-semibold max-md:ml-2.5">
          About
        </h2>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/33b38d7f9fa164ced56b8a919bba17f155f6367655d327d56d14f70b33f9782d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          alt=""
          className="object-contain mt-4 w-full aspect-[333.33] stroke-[1px] stroke-zinc-300 max-md:ml-1.5"
        />
        <p className="mt-5 text-xs leading-5 max-md:mr-1.5">
          Where Blockchain Developers Meet, Ideas Compete, and Innovation
          TriumphsJoin us at Devmatch 2024, a pivotal event hosted by the Asia
          Pacific University Blockchain & Cryptocurrency Club, where the
          brightest student minds across Malaysia converge to tackle the future
          of blockchain technology. From August 16th to 18th, participants will
          dive into an intense journey of coding, collaborating, and competing,
          using their skills to solve real-world problems presented by
          multinational corporations. This hackathon not only aims to deepen
          participants' understanding of blockchain and cryptocurrencies through
          interactive workshops and mentorship but also fosters a vibrant
          community ...{" "}
          <button className="font-semibold text-sky-500">Read More</button>
        </p>
      </div>
    </section>
  );
};

export default AboutSection;
