"use client";
/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import SearchBar from "./SearchBar";
import AboutSection from "./AboutSection";
import ImageSection from "./ImageSection";
import Image from "next/image";
import useWallet from "@/lib/useWallet";

const MainContent: React.FC = () => {
  const { wallet, isLoading, isError } = useWallet();
  const [register, setRegister] = useState<boolean>(false);

  const handleMintCertificate = () => {
    alert("Certificate minted!");
  };

  return (
    <main className="flex flex-col ml-5 w-[100%] max-md:ml-0 max-md:w-full">
      <div className="grid grid-cols-2 max-w-7xl gap-8">
        <Image
          src={"/event_image.png"}
          width={1370}
          height={690}
          alt="hackathon image"
          className=""
        />

        <div></div>

        <div className="flex flex-col space-y-4">
          <h2 className="text-3xl font-bold">About</h2>
          <p className="text-md">
            Where Blockchain Developers Meet, Ideas Compete, and Innovation
            Triumphs. Join us at Devmatch 2024, a pivotal event hosted by the
            Asia Pacific University Blockchain & Cryptocurrency Club, where the
            brightest student minds across Malaysia converge to tackle the
            future of blockchain technology. From August 16th to 18th,
            participants will dive into an intense journey of coding,
            collaborating, and competing, using their skills to solve real-world
            problems presented by multinational corporations. This hackathon not
            only aims to deepen participants&apos; understanding of blockchain
            and cryptocurrencies through interactive workshops and mentorship
            but also fosters a vibrant community.
          </p>
        </div>

        {register ? (
          <div className="flex flex-col space-y-4 bg-white rounded-lg p-8 h-[400px]">
            <h1 className="font-display text-5xl">Devmatch Hackathon</h1>
            <p className="font-lg">
              Build your dreams with blockchain mindset.
            </p>
            <p className="font-lg">Date: 16 - 17 Aug</p>
            <p className="font-lg h-full">Status: Concluded</p>
            <button
              onClick={handleMintCertificate}
              className="bg-cyan-500 p-4 text-xl rounded-full"
            >
              Mint Certificate
            </button>
          </div>
        ) : (
          <div className="flex flex-col space-y-4 bg-white rounded-lg p-8 h-[400px]">
            <h1 className="font-display text-5xl">Devmatch Hackathon</h1>
            <p className="font-lg">
              Build your dreams with blockchain mindset.
            </p>
            <p className="font-lg">Date: 16 - 17 Aug</p>
            <p className="font-lg h-full">Status: Registrations Open</p>
            <button
              onClick={() => {
                setRegister(true);
              }}
              className="bg-cyan-500 p-4 text-xl rounded-full"
            >
              Apply Now
            </button>
          </div>
        )}
      </div>
      <div></div>
    </main>
  );
};

export default MainContent;
