/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "./SearchBar";
import AboutSection from "./AboutSection";
import ImageSection from "./ImageSection";

const MainContent: React.FC = () => {
  return (
    <main className="flex flex-col ml-5 w-[100%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col mt-2.5 w-full max-md:mt-6 max-md:max-w-full">
        <SearchBar />
        <div className="flex flex-col pl-4 mt-16 w-full max-md:mt-10 max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/10fde738095a22c9682364d31199ee390f9105e2fc7b0eaa2890221c87caec1b?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
            alt=""
            className="object-contain max-w-full aspect-[2] w-[688px]"
          />
          <div className="mt-2.5 ml-4 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col">
              <AboutSection />
              <ImageSection />
            </div>
          </div>
        </div>
      </div>
    </main>
  );
};

export default MainContent;
