/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ChatInput: React.FC = () => {
  return (
    <form className="flex flex-col p-3.5 mt-10 max-w-full bg-white rounded-none shadow-[0px_-4px_16px_rgba(0,0,0,0.08)] text-neutral-700 w-[840px] max-md:mt-10">
      <div className="flex flex-wrap gap-2 items-start w-full text-xs font-semibold max-md:max-w-full">
        <button className="flex-1 shrink gap-2 self-stretch px-3.5 py-1.5 bg-gray-100 rounded-lg min-w-[240px] shadow-[0px_1px_0px_rgba(0,0,0,0.12)] max-md:max-w-full">
          🤔 i had update the latest version of paper how is your opinion ?
        </button>
        <button className="gap-2 self-stretch px-3.5 py-1.5 bg-gray-100 rounded-lg min-w-[240px] shadow-[0px_1px_0px_rgba(0,0,0,0.12)]">
          alright,I will. Thanks again for your guidance.
        </button>
        <button className="gap-2 self-stretch px-3.5 py-1.5 bg-gray-100 rounded-lg shadow-[0px_1px_0px_rgba(0,0,0,0.12)]">
          🙋‍♂️ FAQs
        </button>
      </div>
      <div className="flex overflow-hidden flex-wrap gap-10 items-start px-5 py-4 mt-1.5 w-full text-base rounded-xl border-t border-gray-100 bg-slate-200 max-md:max-w-full">
        <input
          type="text"
          placeholder="Type your message here..."
          className="flex-grow bg-transparent outline-none"
          aria-label="Type your message"
        />
        <button type="submit" aria-label="Send message">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/137682b6174aa56dbdcd98c888ddbb669b9697f7f6a24d46b3553120c5a273e5?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
            alt=""
            className="object-contain shrink-0 w-5 aspect-[1.05]"
          />
        </button>
      </div>
    </form>
  );
};

export default ChatInput;
