/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ChatMessage from "./ChatMessage";
import ChatInput from "./ChatInput";

const ChatWindow: React.FC = () => {
  return (
    <section className="flex flex-col ml-5 w-4/5 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col w-full max-md:max-w-full">
        <div className="self-end w-full max-w-[1095px] max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[37%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col mt-32 w-full max-md:mt-10">
                <h2 className="self-end text-3xl leading-none text-black">
                  Dr. Smith
                </h2>
                <div className="flex mt-40 max-w-full w-[295px] max-md:mt-10">
                  <div className="flex flex-1 flex-auto gap-1 items-start self-end mt-40 mr-0 max-md:mt-10">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/8123d45cd691d1382624c484224c270e2158df95819c3e5e277b5ac14351b0f1?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                      alt=""
                      className="object-contain w-7 aspect-square"
                    />
                  </div>
                  <div className="flex flex-col flex-1 grow shrink-0 pb-5 basis-0 w-fit">
                    <ChatMessage
                      content="Proof of Work (PoW) and Proof of Stake (PoS) differ significantly in energy efficiency and network security. PoW requires miners to solve complex puzzles, consuming substantial energy and raising environmental concerns. In contrast, PoS is more energy-efficient, relying on validators who are selected based on the amount of cryptocurrency they stake, reducing energy usage."
                      timestamp="7:20"
                      isUser={false}
                    />
                    <div className="flex z-10 gap-2 items-start self-end p-1 mt-0 rounded-lg bg-zinc-700">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/69d9fdb32b58be7caaa00be6856869d389d4d02ecbe5a45dedef552d96a8b299?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                        alt=""
                        className="object-contain shrink-0 w-3.5 aspect-square"
                      />
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/00b747bbba67a15a6e68988b647df3d21c8c62e999fa122efd248ba1f287fb27?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                        alt=""
                        className="object-contain shrink-0 aspect-[0.93] w-[13px]"
                      />
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e9609ea6aad1d57e915cd9c31a80dc949b6e77bd7d616ead63d682694f79880b?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                        alt=""
                        className="object-contain shrink-0 aspect-[0.93] w-[13px]"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-[63%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col w-full max-md:mt-6 max-md:max-w-full">
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/c02002a338470f79c52ef230cd3d751878db7ac732a0197d355b22dc6023e52d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                  alt=""
                  className="object-contain self-center aspect-[1.15] w-[23px]"
                />
                <div className="flex z-10 flex-wrap items-center mt-12 w-full max-md:mt-10 max-md:mr-2.5 max-md:max-w-full">
                  <ChatMessage
                    content="Good morning dr smith You mentioned that it lacks critical analysis and that some sources are outdated. Could you elaborate on what specific changes you would like to see?"
                    timestamp="7:20"
                    isUser={true}
                  />
                  <div className="flex gap-2 items-center self-stretch my-auto max-md:-mr-2">
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/8454bae28a1c0424da679e42d0795b79ff9cccc0eb264fd9f8a85b8ed4c3081c?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                      alt="User avatar"
                      className="object-contain self-stretch my-auto w-10 aspect-square rounded-[1000px]"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <ChatInput />
    </section>
  );
};

export default ChatWindow;
