/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ShareContentItemProps {
  icon: string;
  title: string;
  description?: string;
}

const ShareContentItem: React.FC<ShareContentItemProps> = ({
  icon,
  title,
  description,
}) => {
  return (
    <div className="flex gap-3 self-start mt-5">
      <img
        src={icon}
        alt=""
        className="object-contain shrink-0 aspect-[1.13] w-[43px]"
      />
      <div className="flex flex-col my-auto">
        <div className="text-sm font-semibold text-zinc-950">{title}</div>
        {description && (
          <div className="mt-2 text-xs font-[450] text-neutral-500">
            {description}
          </div>
        )}
      </div>
    </div>
  );
};

export default ShareContentItem;
