/**
 * This code was generated by Builder.io.
 */
export const shareContentItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/fc746ffda33ef29330f45851d1e1442228398a9d6d57cdab34bfa274d5aafc15?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    title: "Camera",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/fbd4df080ac0867e736746d36ed849fff97afbf3c5847fd1b6d44f5431e2aae1?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    title: "Documents",
    description: "Share your files",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/40cb4550d222981707b1c1ed5aceac9f00e0d2c8fa3af975f4f25b623f5b7c0d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    title: "Create a poll",
    description: "Create a poll for any querry",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ba42cd160997ddd482d0d5c3d0a2773b261fa54137833e5d2c8e4c1689706a44?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    title: "Media",
    description: "Share photos and videos",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/3d2f34e1a5c8c669e156d373155149b32b96064a7e582a3232728bcb285582cc?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    title: "Location",
    description: "Share your location",
  },
];
