/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ShareContentItem from "./ShareContentItem";
import { shareContentItems } from "./shareContentData";

const ShareContent: React.FC = () => {
  return (
    <section className="flex flex-col self-stretch pt-6 pb-24 leading-none bg-white rounded-[40px_40px_0px_0px]">
      <h2 className="self-center text-base font-medium text-zinc-950">
        Share Content
      </h2>
      <div className="flex flex-col pl-6 mt-6 w-full max-md:pl-5">
        {shareContentItems.map((item, index) => (
          <React.Fragment key={index}>
            <ShareContentItem {...item} />
            {index < shareContentItems.length - 1 && (
              <hr className="shrink-0 self-end mt-4 max-w-full h-px border border-solid border-neutral-100 w-[285px]" />
            )}
          </React.Fragment>
        ))}
      </div>
    </section>
  );
};

export default ShareContent;
