/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Sidebar from "../Sidebar/Sidebar";
import MainContent from "../MainContent/MainContent";

const Layout: React.FC = () => {
  return (
    <div className="pr-12 bg-white max-md:pr-5">
      <div className="flex gap-5 max-md:flex-col">
        <Sidebar />
        <MainContent />
      </div>
    </div>
  );
};

export default Layout;
