/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SidebarItem from "./SidebarItem";
import { sidebarItems } from "./sidebarData";

interface SidebarProps {
  username: string;
}

const Sidebar: React.FC<SidebarProps> = ({ username }) => {
  return (
    <aside className="flex flex-col w-1/5 max-md:ml-0 max-md:w-full">
      <nav className="flex overflow-hidden flex-col grow mt-9 w-full text-base font-semibold text-white bg-white border-r border-neutral-200">
        <div className="flex overflow-hidden flex-col bg-white border-r border-neutral-200">
          <div className="flex flex-col items-start pt-7 pr-1.5 pb-24 w-full bg-slate-900 rounded-[76px]">
            <div className="flex-1 shrink gap-2.5 px-3.5 py-2.5 whitespace-nowrap rounded-md border-white border-l-[5px]">
              Home
            </div>
            <div className="z-10 flex-1 shrink gap-2.5 px-3.5 py-2.5 mt-0 whitespace-nowrap rounded-md border-white border-l-[5px]">
              Home
            </div>
            <h1 className="z-10 -mt-6 ml-4 text-3xl tracking-tight text-zinc-100 max-md:ml-2.5">
              Skill³
            </h1>
            <ul className="flex flex-col self-stretch mt-14 w-full text-xl font-medium max-md:mt-10">
              {sidebarItems.map((item, index) => (
                <SidebarItem key={index} {...item} />
              ))}
            </ul>
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/806a62aeab22292b8114173ff0bb3945f7808ce63a80aedcc06ae9b5dc5a97c2?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain self-start mt-6 w-full aspect-[250]"
            />
            <button className="flex overflow-hidden gap-2.5 self-start px-3.5 py-2.5 mt-4 text-base whitespace-nowrap min-h-[39px] max-md:ml-2.5">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/058f961c7d1d4f74f90ccbf4ba404ddb58666a51e2c19537fd08b6d5297471ff?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain shrink-0 my-auto w-5 aspect-square"
              />
              <span className="flex-1 shrink basis-0">Logout</span>
            </button>
          </div>
        </div>
      </nav>
    </aside>
  );
};

export default Sidebar;
