/**
 * This code was generated by Builder.io.
 */
export const sidebarItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7c92369057e737392e976ef6bc76de25c1ed6e93ba3363b2ce39580387deff92?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "New Skill",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7a04d0f9ee0143e6ed7ebe680fb470487efd0f3f3af243f155f2ab2b5786b05d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Expert",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4e9926d1be32e7c01564b694e7bada9908ee17096658aad5fef4730b07bf0797?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Progress",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b2ff53d3c9ee0416adf3996bb5748c9c8f9ae005356f2c72ffed38c432e7b05d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Chat",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7ad1da3307bad9229a5f7fdb00e5a5a389b41fee60d4278943e307785153ad37?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Announcements",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/9f3dcb2613ace73f8619881e6ed741545b9b5b450f7d004ba94271d98be87b33?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Account settings",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/69b7121846e053fdbca7e3910505c8a6521482a822c8d66a2e83f69d80fa406f?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Notification preferences",
  },
];
