/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SidebarItem from "./SidebarItem";
import SidebarSection from "./SidebarSection";

const Sidebar: React.FC = () => {
  const academicItems = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/6f78caa8aae224418b0b45bc41b73ff6ffd1a1d581245cadfd5efaa924fb5ea9?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      text: "New Skill",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c62e3d12621935fe7c69bdc9e7e6eafaa47ced00ae7e66d3f38608e356cb882a?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      text: "Expert",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/5756759a87369e5d1d8456e868e3662cf0db58710992781cb8474dced3fc85b8?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      text: "Progress",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/0ac4b18b50851a3b4bce9e1e463808261a3547f21b415e6effffb3efee4b8478?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      text: "Chat",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/8babeaa09d24c834ef46b841b405f06eb16f96eb22a12aaace7640afb12a55f4?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      text: "Announcements",
    },
  ];

  const settingsItems = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/d74bc400082c2bf6c73c51c40e6083259988fa242b94f777557be2bcb35ccebe?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      text: "Account settings",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4abf713e062d63303270ac3ca311df5587cf0c7338983f6f25abaf8052b0e942?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      text: "Notification preferences",
      className: "text-teal-500",
    },
  ];

  return (
    <nav className="flex flex-col w-[23%] max-md:ml-0 max-md:w-full">
      <div className="flex overflow-hidden flex-col grow w-full text-base font-semibold text-white bg-white border-r border-neutral-200 max-md:mt-3.5">
        <div className="flex overflow-hidden flex-col bg-white border-r border-neutral-200">
          <div className="flex flex-col items-start pt-7 pr-1.5 pb-24 w-full bg-slate-900 rounded-[76px]">
            <div className="flex-1 shrink gap-2.5 px-3.5 py-2.5 whitespace-nowrap rounded-md border-white border-l-[5px]">
              Home
            </div>
            <div className="z-10 flex-1 shrink gap-2.5 px-3.5 py-2.5 mt-0 whitespace-nowrap rounded-md border-white border-l-[5px]">
              Home
            </div>
            <h1 className="z-10 -mt-6 ml-4 text-3xl tracking-tight text-zinc-100 max-md:ml-2.5">
              Skill³
            </h1>
            <div className="flex flex-col self-stretch mt-14 w-full text-xl font-medium max-md:mt-10">
              <div className="flex flex-col items-start pr-12 pl-5 w-full font-semibold whitespace-nowrap max-md:pr-5">
                <SidebarItem
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/e1b14c5d114448c41f75774c6c3039262ffdb04589eedf2ee558adb11e05f3a7?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                  text="Home"
                />
                <SidebarItem
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/e1b14c5d114448c41f75774c6c3039262ffdb04589eedf2ee558adb11e05f3a7?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                  text="Dashboard"
                />
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/65202168aab88bd2cf4b3af333e951f187227c9112e2247883e1fce288a30599?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-5 w-full max-md:mr-1.5"
              />
              <SidebarSection title="ACADEMIC" items={academicItems} />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/8079025b46cd1b9dfeb24fbd326b42c400a6d7451fde99f64b29efbe285fe46e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-1.5 w-full aspect-[250]"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/82a6eb4b486b708b34f6a447b8d0ce8a768261f2d9881380e1424491516f0011?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain self-start mt-36 w-full aspect-[250] max-md:mt-10"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/72bee63fa8fd87abb25256e4f3077a34a8b9dc39da988e0bc5a1c7b6b353dbb3?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-3.5 w-full aspect-[250]"
              />
              <SidebarSection title="SETTINGS" items={settingsItems} />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/806a62aeab22292b8114173ff0bb3945f7808ce63a80aedcc06ae9b5dc5a97c2?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain self-start mt-6 w-full aspect-[250]"
              />
              <SidebarItem
                icon="https://cdn.builder.io/api/v1/image/assets/TEMP/61e540aecfaca4bb9beecd2a0b718ee7ec4b22d40d2c4f694b6cb1bfba52b8ca?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                text="Logout"
                className="self-start mt-4 max-md:ml-2.5"
              />
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Sidebar;
