/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SkillCardProps {
  title: string;
  imageSrc: string;
}

const SkillCard: React.FC<SkillCardProps> = ({ title, imageSrc }) => {
  return (
    <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col grow px-9 pt-5 pb-5 w-full text-2xl font-bold text-black bg-zinc-300 max-md:px-5 max-md:mt-10">
        <img
          loading="lazy"
          src={imageSrc}
          alt={title}
          className="object-contain w-full aspect-[2.2]"
        />
        <div className="mt-2.5 self-center">{title}</div>
      </div>
    </div>
  );
};

export default SkillCard;
