import React from "react";
import Link from "next/link";

const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated by{" "}
        <span href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </span>
        . Quickly use the links below to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/dashboard">
            <span style={{ color: "#87CEFA", textDecoration: "none" }}>Dashboard</span>
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/accountsettings">
            <span style={{ color: "#87CEFA", textDecoration: "none" }}>Account Settings</span>
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/BlockchainVerifier">
            <span style={{ color: "#87CEFA", textDecoration: "none" }}>New Skill</span>
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/NotificationPeferences">
            <span style={{ color: "#87CEFA", textDecoration: "none" }}>Home1</span>
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link href="/openforevent">
            <span style={{ color: "#87CEFA", textDecoration: "none" }}>Open for Event</span>
          </Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
