/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Sidebar from "./Sidebar";
import VerifierInput from "./VerifierInput";
import TransactionTable from "./TransactionTable";
import Pagination from "./Pagination";

const BlockchainVerifier: React.FC = () => {
  return (
    <div className="pr-20 bg-white max-md:pr-5">
      <div className="flex gap-5 max-md:flex-col">
        <Sidebar />
        <main className="flex flex-col ml-5 w-[77%] max-md:ml-0 max-md:w-full">
          <section className="flex flex-col mt-28 w-full max-md:mt-10 max-md:max-w-full">
            <h1 className="self-center text-2xl font-medium text-black max-md:max-w-full">
              Blockchain certificate Universal Verifier
            </h1>
            <VerifierInput />
            <TransactionTable />
            <Pagination />
          </section>
        </main>
      </div>
    </div>
  );
};

export default BlockchainVerifier;
