/**
 * This code was generated by Builder.io.
 */
import React from "react";

const VerifierInput: React.FC = () => {
  return (
    <form className="flex flex-wrap gap-5 justify-between self-center py-px pl-8 mt-6 max-w-full text-2xl font-medium bg-zinc-300 w-[586px] max-md:pl-5">
      <label htmlFor="certificateUrl" className="my-auto text-black">
        Certificate url
      </label>
      <input
        type="text"
        id="certificateUrl"
        className="sr-only"
        aria-label="Certificate url"
      />
      <button
        type="submit"
        className="px-3.5 py-3 text-white whitespace-nowrap bg-green-400 max-md:pr-5"
      >
        Verify
      </button>
    </form>
  );
};

export default VerifierInput;
