/**
 * This code was generated by Builder.io.
 */
import React from "react";

const AnnouncementsHeader: React.FC = () => {
  return (
    <header>
      <h1 className="self-start text-xl font-semibold tracking-normal text-black">
        Announcements
      </h1>
      <div className="flex flex-wrap gap-5 justify-between mt-4 w-full max-md:max-w-full">
        <div className="flex flex-wrap gap-4 text-base text-zinc-500 max-md:max-w-full">
          <div className="flex flex-auto gap-3 items-center py-2 pr-4 pl-3 bg-white rounded-lg border border-solid border-neutral-200 min-h-[40px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7d180ede1e5a24e1790ffc4498c2d09888ca77d75df2507d9db1d38978cc0fcb?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
            />
            <input
              type="text"
              placeholder="Search title..."
              className="flex-1 shrink self-stretch my-auto basis-0 text-ellipsis bg-transparent border-none"
              aria-label="Search title"
            />
          </div>
          <button className="flex gap-3 items-center py-2 pr-4 pl-3 whitespace-nowrap bg-white rounded-lg border border-solid border-neutral-200 min-h-[40px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/c3769edf7918fc94cc4b94e8e9b3ef13453f736fe745d3894845055e1edc161a?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
            />
            <span className="self-stretch my-auto text-ellipsis">Filter</span>
          </button>
        </div>
        <div className="flex items-start p-1 rounded-lg bg-neutral-100">
          <button className="flex gap-2 items-center px-3 w-12 bg-white rounded shadow-sm min-h-[32px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/f88980b68a3be11ada347d30c96634d6e536d9ce892de4c750dfac97dd31992d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain self-stretch my-auto w-6 aspect-square"
            />
          </button>
          <button className="flex gap-2 items-center px-3 w-12 rounded min-h-[32px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/af32cd91bd07ec2fa54bb1a3f6d486af27ed2819b9fe91cc488a0859c1aba768?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain self-stretch my-auto w-6 aspect-square"
            />
          </button>
          <button className="flex gap-2 items-center px-3 w-12 rounded min-h-[32px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d48c0dbb27a82e28b4fcc98cf0ab708676b8478e6bd87b8965777a250a40c33c?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain self-stretch my-auto w-6 aspect-square"
            />
          </button>
        </div>
      </div>
    </header>
  );
};

export default AnnouncementsHeader;
