/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Layout from "./Layout";
import TaskList from "./TaskList";

const App: React.FC = () => {
  return (
    <Layout>
      <TaskList />
    </Layout>
  );
};

export default App;
