/**
 * This code was generated by Builder.io.
 */
import React from "react";
import AnnouncementsHeader from "./AnnouncementsHeader";
import TaskList from "./TaskList";

interface MainContentProps {
  children: React.ReactNode;
}

const MainContent: React.FC<MainContentProps> = ({ children }) => {
  return (
    <main className="flex flex-col ml-5 w-[78%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col self-stretch my-auto w-full max-md:mt-10 max-md:max-w-full">
        <AnnouncementsHeader />
        <TaskList />
        {children}
      </div>
    </main>
  );
};

export default MainContent;
