/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SidebarSectionProps {
  title: string;
  children: React.ReactNode;
}

const SidebarSection: React.FC<SidebarSectionProps> = ({ title, children }) => {
  return (
    <div className="flex flex-col items-start px-5 mt-7 w-full max-md:pr-5">
      <h2>{title}</h2>
      {children}
    </div>
  );
};

export default SidebarSection;
