/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SidebarItemProps {
  icon: string;
  text: string;
  className?: string;
}

const SidebarItem: React.FC<SidebarItemProps> = ({
  icon,
  text,
  className = "",
}) => {
  return (
    <div
      className={`flex overflow-hidden gap-2.5 px-3.5 py-2.5 rounded-md min-h-[39px] ${className}`}
    >
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain shrink-0 my-auto w-5 aspect-square"
      />
      <div className="flex-1 shrink basis-0">{text}</div>
    </div>
  );
};

export default SidebarItem;
