/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SidebarItem from "./SidebarItem";

interface SidebarSectionProps {
  title: string;
  items: Array<{ icon: string; text: string; className?: string }>;
}

const SidebarSection: React.FC<SidebarSectionProps> = ({ title, items }) => {
  return (
    <div className="flex flex-col items-start px-5 mt-7 w-full max-md:pr-5">
      <div>{title}</div>
      {items.map((item, index) => (
        <SidebarItem
          key={index}
          icon={item.icon}
          text={item.text}
          className={item.className}
        />
      ))}
    </div>
  );
};

export default SidebarSection;
