/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TaskItem from "./TaskItem";

const tasks = [
  {
    id: "FIG-123",
    title: "Complete course with coursera",
    progress: 3,
    priority: "High",
    date: "June 11",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    id: "FIG-122",
    title: "answer quiz",
    progress: 5,
    priority: "Low",
    date: "June 11",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    id: "FIG-120",
    title: "complete assignments",
    progress: 2,
    priority: "Low",
    date: "June 9",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    id: "FIG-119",
    title: "discuss with mentor and friends",
    progress: 1,
    priority: "Medium",
    date: "June 5",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    id: "FIG-118",
    title: "change and complete task on time",
    progress: 5,
    priority: "Medium",
    date: "June 5",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    id: "FIG-115",
    title: "Revise copy on About page",
    progress: 4,
    priority: "Low",
    date: "May 25",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    id: "FIG-114",
    title: "Publish HackerNews post",
    progress: 2,
    priority: "Low",
    date: "May 21",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    id: "FIG-113",
    title: "Review image licensing for header section images",
    progress: 3,
    priority: "High",
    date: "May 19",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    id: "FIG-112",
    title: "Accessibility focused state for input fields",
    progress: 5,
    priority: "High",
    date: "May 16",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    id: "FIG-111",
    title: "Header IA revision to support addition of blog page",
    progress: 1,
    priority: "High",
    date: "May 8",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    id: "FIG-110",
    title: "Press outbound",
    progress: 3,
    priority: "Medium",
    date: "May 5",
    owner:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0adb95ea9220904e2f9431d445470344cbb4385928c8a75c34167b3ee397f087?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
];

const TaskList: React.FC = () => {
  return (
    <section className="mt-5 mr-6 max-md:mr-2.5 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-[39%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col items-start w-full text-base font-medium max-md:mt-10">
            {tasks.map((task) => (
              <div key={task.id} className="flex gap-8 mt-8 first:mt-0">
                <div className="flex-col whitespace-nowrap text-zinc-500">
                  {task.id}
                </div>
                <div className="flex-col text-black">{task.title}</div>
              </div>
            ))}
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[61%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col w-full max-md:mt-10 max-md:max-w-full">
            <div className="flex flex-wrap gap-5">
              <div className="flex flex-col">
                <div className="self-center text-base font-medium text-black">
                  Progress
                </div>
              </div>
              <div className="flex flex-col grow shrink-0 basis-0 w-fit">
                <div className="flex gap-10 self-end mr-11 text-base font-medium text-black whitespace-nowrap max-md:mr-2.5">
                  <div>Priority</div>
                  <div className="text-right">Date</div>
                  <div className="text-center">Owner</div>
                </div>
              </div>
            </div>
            {tasks.map((task) => (
              <TaskItem key={task.id} {...task} />
            ))}
          </div>
        </div>
      </div>
      <button className="gap-2 self-end px-4 mt-20 mr-12 text-base font-medium text-white whitespace-nowrap bg-teal-500 rounded-lg min-h-[40px] shadow-[0px_4px_4px_rgba(0,0,0,0.25)] max-md:mt-10 max-md:mr-2.5">
        Next
      </button>
    </section>
  );
};

export default TaskList;
