/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface TaskItemProps {
  progress: number;
  priority: string;
  date: string;
  owner: string;
}

const TaskItem: React.FC<TaskItemProps> = ({
  progress,
  priority,
  date,
  owner,
}) => {
  const priorityColor = {
    High: "bg-teal-500",
    Medium: "bg-cyan-400",
    Low: "bg-cyan-400",
  }[priority];

  return (
    <div className="flex flex-wrap gap-10 mt-6 w-full max-md:mr-1 max-md:max-w-full">
      <div className="flex flex-auto gap-5">
        {progress > 0 && (
          <div className="flex gap-2 justify-center items-center px-2 py-2.5 bg-white rounded-lg border border-solid border-neutral-200 min-h-[32px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ad8e09029b49d36475c2955b52bd3e9bc0482453573dcccdd70cdf77f58e4b5a?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain self-stretch my-auto aspect-square w-[15px]"
            />
          </div>
        )}
        {progress > 1 && (
          <div className="flex gap-2 justify-center items-center px-2 py-2.5 bg-white rounded-lg border border-solid border-neutral-200 min-h-[32px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ad8e09029b49d36475c2955b52bd3e9bc0482453573dcccdd70cdf77f58e4b5a?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain self-stretch my-auto aspect-square w-[15px]"
            />
          </div>
        )}
        {progress > 2 && (
          <div className="flex gap-2 justify-center items-center px-2 py-2.5 bg-white rounded-lg border border-solid border-neutral-200 min-h-[32px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ad8e09029b49d36475c2955b52bd3e9bc0482453573dcccdd70cdf77f58e4b5a?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain self-stretch my-auto aspect-square w-[15px]"
            />
          </div>
        )}
        {progress > 3 && (
          <div className="flex gap-2 justify-center items-center px-2 py-2.5 bg-white rounded-lg border border-solid border-neutral-200 min-h-[32px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ad8e09029b49d36475c2955b52bd3e9bc0482453573dcccdd70cdf77f58e4b5a?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain self-stretch my-auto aspect-square w-[15px]"
            />
          </div>
        )}
        {progress > 4 && (
          <div className="flex gap-2 justify-center items-center px-2 py-2.5 bg-white rounded-lg border border-solid border-neutral-200 min-h-[32px]">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ad8e09029b49d36475c2955b52bd3e9bc0482453573dcccdd70cdf77f58e4b5a?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              alt=""
              className="object-contain self-stretch my-auto aspect-square w-[15px]"
            />
          </div>
        )}
        <div
          className={`gap-2 self-stretch px-2 py-1.5 my-auto text-xs font-semibold leading-none text-white whitespace-nowrap ${priorityColor} rounded-lg border border-solid border-neutral-200`}
        >
          {priority}
        </div>
      </div>
      <div className="flex gap-3 self-start text-base text-right text-zinc-500">
        <div className="grow">{date}</div>
        <img
          loading="lazy"
          src={owner}
          alt="Task owner"
          className="object-contain shrink-0 self-start max-w-full aspect-[3.75] w-[105px]"
        />
      </div>
    </div>
  );
};

export default TaskItem;
