/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ChatListItem from "./ChatListItem";
import { chatListItems } from "./chatListData";

const ChatList: React.FC = () => {
  return (
    <aside className="flex overflow-hidden flex-col self-end pt-16 max-w-full bg-white border-r border-neutral-200 w-[387px]">
      <div className="flex gap-3 items-center self-start py-2 pr-4 pl-3 ml-6 text-base bg-white rounded-lg border border-solid border-neutral-200 min-h-[40px] text-zinc-500 max-md:ml-2.5">
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/7d180ede1e5a24e1790ffc4498c2d09888ca77d75df2507d9db1d38978cc0fcb?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-6 aspect-square"
        />
        <input
          type="search"
          placeholder="Search chats"
          className="flex-1 shrink self-stretch my-auto basis-0 text-ellipsis bg-transparent outline-none"
          aria-label="Search chats"
        />
      </div>
      <ul className="flex flex-col mt-6 w-full">
        {chatListItems.map((item, index) => (
          <ChatListItem key={index} {...item} />
        ))}
      </ul>
    </aside>
  );
};

export default ChatList;
