/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface ChatListItemProps {
  avatar: string;
  name: string;
  lastMessage: string;
}

const ChatListItem: React.FC<ChatListItemProps> = ({
  avatar,
  name,
  lastMessage,
}) => {
  return (
    <li className="flex gap-4 items-center py-3 pr-1 pl-4 w-full rounded-lg">
      <img
        src={avatar}
        alt={`${name}'s avatar`}
        className="object-contain shrink-0 self-stretch my-auto w-16 aspect-square rounded-[1000px]"
      />
      <div className="flex flex-col flex-1 shrink self-stretch my-auto basis-0 min-w-[240px]">
        <h3 className="text-xl font-medium text-black">{name}</h3>
        <p className="text-base text-zinc-700">{lastMessage}</p>
      </div>
    </li>
  );
};

export default ChatListItem;
