/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SidebarItemProps {
  icon: string;
  label: string;
}

const SidebarItem: React.FC<SidebarItemProps> = ({ icon, label }) => {
  return (
    <li className="flex overflow-hidden gap-2.5 px-3.5 py-2.5 mt-2.5 whitespace-nowrap rounded-md min-h-[39px]">
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain shrink-0 my-auto w-5 aspect-square"
      />
      <div className="flex-1 shrink basis-0">{label}</div>
    </li>
  );
};

export default SidebarItem;
