/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface SidebarItemProps {
  icon: string;
  text: string;
  isActive?: boolean;
  color?: string;
}

const SidebarItem: React.FC<SidebarItemProps> = ({
  icon,
  text,
  isActive = false,
  color = "white",
}) => {
  const borderColor = isActive ? `border-${color}-500` : `border-${color}`;
  const textColor = isActive ? `text-${color}-500` : `text-${color}`;

  return (
    <div
      className={`flex gap-2.5 px-3.5 py-2.5 rounded-md border-l-[5px] ${borderColor} ${textColor}`}
    >
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain shrink-0 my-auto w-5 aspect-square"
      />
      <div className="flex-1 shrink basis-0">{text}</div>
    </div>
  );
};

export default SidebarItem;
