/**
 * This code was generated by Builder.io.
 */
export const sidebarItems = [
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/d34c7e42120de783065fe20ea509c5fe8b97e4678085e368e4f31fff339f8df0?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "New Skill",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7a04d0f9ee0143e6ed7ebe680fb470487efd0f3f3af243f155f2ab2b5786b05d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Expert",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/4e9926d1be32e7c01564b694e7bada9908ee17096658aad5fef4730b07bf0797?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Progress",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/ccabec12dcbdf258c9e1836b885ac0377e1ffb0e32be46113728bcb67df3d057?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Chat",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/7ad1da3307bad9229a5f7fdb00e5a5a389b41fee60d4278943e307785153ad37?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Announcements",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/1a47f3234068e57d66c913fd8f07449b3c40b46b0a13c5542018f11847b83189?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Account settings",
  },
  {
    icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/69b7121846e053fdbca7e3910505c8a6521482a822c8d66a2e83f69d80fa406f?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    label: "Notification preferences",
  },
];
