/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Header: React.FC = () => {
  return (
    <header className="flex flex-wrap gap-5 justify-between py-6 pr-8 pl-20 w-full text-lg leading-8 text-black bg-zinc-100 max-md:px-5 max-md:max-w-full">
      <div className="my-auto">Skill 3</div>
      <button className="px-12 py-3 rounded-xl border border-black border-solid bg-zinc-100 max-md:px-5">
        Sign Up
      </button>
    </header>
  );
};

export default Header;
