/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SidebarSection from "./SidebarSection";
import SidebarItem from "./SidebarItem";

type SidebarProps = {
  activeSection: string;
};

const Sidebar: React.FC<SidebarProps> = ({ activeSection }) => {
  const academicItems = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b68ce8b5ed19c79e2285ba479d6ca2054a107846da3faed6b9de199328fa04e6?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      label: "New Skill",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/b3be24f8f2f4babf8ea143e1cd6e69b161bd70e9ca460afad2b9497f54eaac25?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      label: "Expert",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/1596e17ce4fcfd316d0963ba95688430d5c9e8231cb9c91fd9d8ad443b625bf9?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      label: "Progress",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a7cd00136ab49eb27b6a34400c7f07518d724d739152da8940d28d4947c0deee?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      label: "Chat",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/eed4648a734703a610f65e0537b5c71f41f30a8c4ca85f1c959e49f2b441049d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      label: "Announcements",
    },
  ];

  const settingsItems = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/5b8dcb653a1fa58786fb043ce9fdb07ebde08e4c1a62eb4f12b18ec224481684?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      label: "Account settings",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/1ee64b8eef68ebdc6a5ded8b764dc64e98af14370436244ab9466b2d5159f3ca?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      label: "Notification preferences",
    },
  ];

  return (
    <aside className="flex flex-col w-[28%] max-md:ml-0 max-md:w-full">
      <nav className="flex overflow-hidden flex-col grow w-full text-base font-semibold bg-white border-r border-neutral-200 max-md:mt-3.5">
        <div className="flex overflow-hidden flex-col bg-white border-r border-neutral-200">
          <div className="flex flex-col items-start pt-7 pr-1.5 pb-24 w-full bg-slate-900 rounded-[76px]">
            <div className="flex-1 shrink gap-2.5 px-3.5 py-2.5 text-white whitespace-nowrap rounded-md border-white border-l-[5px]">
              Home
            </div>
            <div className="z-10 flex-1 shrink gap-2.5 px-3.5 py-2.5 mt-0 text-white whitespace-nowrap rounded-md border-white border-l-[5px]">
              Home
            </div>
            <h1 className="z-10 -mt-6 ml-4 text-3xl tracking-tight text-zinc-100 max-md:ml-2.5">
              Skill³
            </h1>
            <div className="flex flex-col self-stretch mt-14 w-full text-xl font-medium max-md:mt-10">
              <div className="flex flex-col items-start pr-12 pl-5 w-full font-semibold whitespace-nowrap max-md:pr-5">
                <SidebarItem
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/4974002084cdf440ce83b6c29bc329cec921c38d3d4d0be6e4d25d0519ed310e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                  label="Home"
                  isActive={activeSection === "home"}
                  activeColor="text-teal-500"
                />
                <SidebarItem
                  icon="https://cdn.builder.io/api/v1/image/assets/TEMP/8c5c232620efa12614b00360cb6c51636dc8a2ee8ccbd9ede41923b6c3c722c6?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                  label="Dashboard"
                  isActive={activeSection === "dashboard"}
                />
              </div>
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/65202168aab88bd2cf4b3af333e951f187227c9112e2247883e1fce288a30599?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-5 w-full max-md:mr-1.5"
              />
              <SidebarSection title="ACADEMIC" items={academicItems} />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/8079025b46cd1b9dfeb24fbd326b42c400a6d7451fde99f64b29efbe285fe46e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-1.5 w-full aspect-[250]"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/82a6eb4b486b708b34f6a447b8d0ce8a768261f2d9881380e1424491516f0011?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain self-start mt-36 w-full aspect-[250] max-md:mt-10"
              />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/72bee63fa8fd87abb25256e4f3077a34a8b9dc39da988e0bc5a1c7b6b353dbb3?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain mt-3.5 w-full aspect-[250]"
              />
              <SidebarSection title="SETTINGS" items={settingsItems} />
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/806a62aeab22292b8114173ff0bb3945f7808ce63a80aedcc06ae9b5dc5a97c2?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain self-start mt-6 w-full aspect-[250]"
              />
              <SidebarItem
                icon="https://cdn.builder.io/api/v1/image/assets/TEMP/89e69481a1556112563466c629226a23ad6aa88fe9d503075ce4192d51e56c64?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                label="Logout"
                className="self-start mt-4 max-md:ml-2.5"
              />
            </div>
          </div>
        </div>
      </nav>
    </aside>
  );
};

export default Sidebar;
