/**
 * This code was generated by Builder.io.
 */
import React from "react";

type SidebarItemProps = {
  icon: string;
  label: string;
  isActive?: boolean;
  activeColor?: string;
  className?: string;
};

const SidebarItem: React.FC<SidebarItemProps> = ({
  icon,
  label,
  isActive = false,
  activeColor = "text-white",
  className = "",
}) => {
  const baseClasses =
    "flex overflow-hidden gap-2.5 px-3.5 py-2.5 mt-2.5 rounded-md min-h-[39px]";
  const activeClasses = isActive
    ? `${activeColor} border-l-[5px] border-${activeColor.replace("text-", "")}`
    : "";

  return (
    <div className={`${baseClasses} ${activeClasses} ${className}`}>
      <img
        loading="lazy"
        src={icon}
        alt=""
        className="object-contain shrink-0 my-auto w-5 aspect-square"
      />
      <div className="flex-1 shrink basis-0">{label}</div>
    </div>
  );
};

export default SidebarItem;
