/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SidebarItem from "./SidebarItem";

type SidebarSectionProps = {
  title: string;
  items: Array<{ icon: string; label: string }>;
};

const SidebarSection: React.FC<SidebarSectionProps> = ({ title, items }) => {
  return (
    <section className="flex flex-col items-start px-5 mt-7 w-full text-white max-md:pr-5">
      <h2>{title}</h2>
      {items.map((item, index) => (
        <SidebarItem key={index} icon={item.icon} label={item.label} />
      ))}
    </section>
  );
};

export default SidebarSection;
