/**
 * This code was generated by Builder.io.
 */
import React from "react";

const HeroSection: React.FC = () => {
  return (
    <section className="flex overflow-hidden items-start w-full bg-slate-900 max-w-[1433px] max-md:max-w-full">
      <div className="min-w-[240px] w-[1433px] max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <div className="flex flex-col w-4/5 max-md:ml-0 max-md:w-full">
            <div className="flex grow items-start pb-1.5 min-h-[798px] max-md:mt-10">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/a97cb0d543f7b304d4907d59da57dadaec53b1121ccd98e1c2c2fc859699bad9?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt="Hero image"
                className="object-contain aspect-[2.05] min-w-[240px] w-[1059px]"
              />
            </div>
          </div>
          <div className="flex flex-col ml-5 w-1/5 max-md:ml-0 max-md:w-full">
            <div className="flex flex-col self-stretch my-auto w-full text-sm font-bold tracking-wider leading-5 text-center text-white uppercase max-md:mt-10">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/b8f69f97f58e3f9defc73c6c00a750d6e87b57b297af28d92f5262853019e868?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt=""
                className="object-contain w-full aspect-[0.93]"
              />
              <button className="py-6 pr-16 pl-16 mt-20 w-24 bg-orange-500 rounded-2xl border-2 border-solid border-zinc-800 shadow-[3px_3px_0px_rgba(46,47,53,1)] max-md:px-5 max-md:mt-10 max-md:mr-0.5">
                Get started
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
