/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import HeroSection from "./HeroSection";
import VerifiedSkillHolders from "./VerifiedSkillHolders";
import WhyUseSkill3 from "./WhyUseSkill3";
import BlockchainSection from "./BlockchainSection";
import BrandFeatures from "./BrandFeatures";

const MainComponent: React.FC = () => {
  return (
    <div className="flex flex-col items-center px-20 pb-12 bg-green-100 max-md:px-5">
      <div className="flex flex-col max-w-full w-[1448px]">
        <Header title="skill 3" />
        <HeroSection />
        <VerifiedSkillHolders />
        <WhyUseSkill3 />
        <BlockchainSection />
        <BrandFeatures />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/651c9b64c13a2f8489e3fb684a233615978fdcfe3621aa4e015b1846c533a7a1?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          alt=""
          className="object-contain w-full aspect-[0.69]"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/83a05a0f2e13de333f45092cac4630f706b02d685726cb29b4d2f7bf1a5e4caa?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          alt=""
          className="object-contain z-10 mt-0 w-full aspect-[0.72] max-md:mt-0 max-md:max-w-full"
        />
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/ac9d2b4095b87dd843be9c6be8ab979cef76a653e2896da6c9982a422f403098?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
          alt=""
          className="object-contain w-full aspect-[5.52] mt-[3481px] max-md:mt-10 max-md:max-w-full"
        />
      </div>
    </div>
  );
};

export default MainComponent;
