/**
 * This code was generated by Builder.io.
 */
export const contacts = [
  {
    name: "Merna",
    message: "Will head to the Help Center...",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/59f205f2caee7a3167c443fd56617577ec801cc9be1ca8b647414151060d7f1b?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    name: "Carlo Emilio",
    message: "Let's go",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/bc427208475800f6c8e715820c0e0c9ef6d49d333ddceeeaca98fbb2505bd9fe?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
  {
    name: "Oscar Davis",
    message: "Trueeeeee",
    avatar:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/0ad37caab6cb29ac796ffd536fc2be7ef65317d00afeeabf0fb923ae622d3153?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
  },
];
