/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface NavigationTabsProps {}

const NavigationTabs: React.FC<NavigationTabsProps> = () => {
  const tabs = [
    {
      label: "Registration",
      className: "px-7 py-1 mt-1 bg-zinc-100 max-md:px-5",
    },
    { label: "Confirmation", className: "px-5 py-1 bg-zinc-100 max-md:pl-5" },
  ];

  return (
    <nav className="flex flex-wrap gap-5 justify-between items-start mt-2.5 max-w-full text-xl font-semibold leading-relaxed text-sky-900 whitespace-nowrap w-[836px]">
      {tabs.map((tab, index) => (
        <button key={index} className={tab.className}>
          {tab.label}
        </button>
      ))}
    </nav>
  );
};

export default NavigationTabs;
