/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import NavigationTabs from "./NavigationTabs";

interface MyComponentProps {}

const MyComponent: React.FC<MyComponentProps> = () => {
  return (
    <div className="flex overflow-hidden flex-col items-center pb-28 bg-white max-md:pb-24">
      <Header />
      <NavigationTabs />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/662a8532fa1b9657dec5fa01299d4dee91fb8b4a9e40106740b209533ae659ab?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
        alt="Design illustration"
        className="object-contain mt-2.5 max-w-full aspect-[1.86] w-[838px]"
      />
    </div>
  );
};

export default MyComponent;
