/**
 * This code was generated by Builder.io.
 */
import React from "react";
import ChatMessage from "./ChatMessage";
import ChatInput from "./ChatInput";

interface ChatWindowProps {
  messages: Array<{
    sender: string;
    content: string;
    timestamp: string;
  }>;
}

const ChatWindow: React.FC<ChatWindowProps> = ({ messages }) => {
  return (
    <section className="flex flex-col ml-5 w-4/5 max-md:ml-0 max-md:w-full">
      <div className="flex flex-col w-full max-md:max-w-full">
        <div className="self-end w-full max-w-[1095px] max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[37%] max-md:ml-0 max-md:w-full">
              <div className="flex flex-col mt-32 w-full max-md:mt-10">
                <h2 className="self-end text-3xl leading-none text-black">
                  Dr. Smith
                </h2>
                <div className="flex mt-40 max-w-full w-[295px] max-md:mt-10">
                  {messages.map((message, index) => (
                    <ChatMessage key={index} {...message} />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <ChatInput />
    </section>
  );
};

export default ChatWindow;
