/**
 * This code was generated by Builder.io.
 */
import React from "react";
import EventCard from "./EventCard";

interface Event {
  date: string;
  day: string;
  title: string;
  time: string;
  location: string;
  imageSrc: string;
  iconSrc: string;
}

interface EventSectionProps {
  events: Event[];
}

const EventSection: React.FC<EventSectionProps> = ({ events }) => (
  <section className="mt-8 w-full max-md:max-w-full">
    <div className="flex gap-5 max-md:flex-col">
      {events.map((event, index) => (
        <EventCard key={index} {...event} />
      ))}
    </div>
  </section>
);

export default EventSection;
