/**
 * This code was generated by Builder.io.
 */
import React from "react";
import TokenCard from "./TokenCard";
import EventSection from "./EventSection";

const MainContent: React.FC = () => {
  const tokenCards = [
    {
      amount: "$1000",
      percentage: "+32.40%",
      label: "Best candidate",
      imgSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/4c2e4e283646c8df685795c9116523cde9c8c378fa84a8604d7b6d2b2f21c0f0?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      footerImgSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/7e1061d06a3d993675dc5b46cf7161b6c0d358a3ffa75ae0da10c2322f3cc95c?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    },
    {
      amount: "$990",
      percentage: "+32.40%",
      label: "Best candidate",
      imgSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/4c2e4e283646c8df685795c9116523cde9c8c378fa84a8604d7b6d2b2f21c0f0?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      footerImgSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/1af8e7a77b08be2c324fee1a236064c5364644285d610fe93044e1a304b7bc9d?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    },
    {
      amount: "$989",
      percentage: "+32.40%",
      label: "Best candidate",
      imgSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/4c2e4e283646c8df685795c9116523cde9c8c378fa84a8604d7b6d2b2f21c0f0?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      footerImgSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/e1926d8d15b3ae3920f55a0e88de579742269a2fe9e5b413a7aabbfa39bca913?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    },
  ];

  const events = [
    {
      date: "Apr",
      day: "20",
      title: "WEB3-CREATING VALUE BOOTCAMP",
      time: "Thu 10:15",
      location: "New York, NY",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/02f7c504e127ea438567b6a18bdbaec5ddcc5ef6b3619044f40878aea138e02e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f4411a9db7e47a3005a1a677889431926a9a0f347099416cd304bc6229a9003f?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    },
    {
      date: "Apr",
      day: "20",
      title: "APU CTF-MATCH COMPETITION",
      time: "Thu 10:15",
      location: "New York, NY",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/02f7c504e127ea438567b6a18bdbaec5ddcc5ef6b3619044f40878aea138e02e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f4411a9db7e47a3005a1a677889431926a9a0f347099416cd304bc6229a9003f?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    },
    {
      date: "Apr",
      day: "20",
      title: "DIGITAL INNOVATION COMPETITION",
      time: "Thu 10:15",
      location: "New York, NY",
      imageSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/02f7c504e127ea438567b6a18bdbaec5ddcc5ef6b3619044f40878aea138e02e?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
      iconSrc:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f4411a9db7e47a3005a1a677889431926a9a0f347099416cd304bc6229a9003f?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a",
    },
  ];

  return (
    <main className="flex flex-col ml-5 w-[79%] max-md:ml-0 max-md:w-full">
      <header className="flex flex-col self-stretch my-auto w-full max-md:mt-10 max-md:max-w-full">
        <div className="w-full max-w-[1062px] max-md:max-w-full">
          <section className="flex gap-5 max-md:flex-col">
            {tokenCards.map((card, index) => (
              <TokenCard key={index} {...card} />
            ))}
          </section>
        </div>
        <section className="flex flex-col pl-1.5 mt-14 w-full max-md:mt-10 max-md:max-w-full">
          <div className="self-start text-xl font-medium text-black max-md:max-w-full">
            Participate in event to network with expert and earn coin!
          </div>
          <EventSection events={events} />
        </section>
      </header>
    </main>
  );
};

export default MainContent;
