/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface TokenCardProps {
  amount: string;
  percentage: string;
  label: string;
  imgSrc: string;
  footerImgSrc: string;
}

const TokenCard: React.FC<TokenCardProps> = ({
  amount,
  percentage,
  label,
  imgSrc,
  footerImgSrc,
}) => (
  <div className="flex grow max-md:mt-10">
    <article className="flex flex-col items-start p-4 mr-0 w-full rounded-2xl shadow-sm bg-[linear-gradient(134deg,#4E4E4E_-16.04%,#333_9.33%,#1A1A1A_32.02%,#1A1A1A_62.06%,#262626_87.42%,#4E4E4E_112.12%)]">
      <div className="flex gap-3 justify-center items-center">
        <div className="flex gap-2.5 items-center self-stretch p-2 my-auto bg-emerald-300 rounded-lg h-[38px] w-[38px]">
          <div className="flex w-6 min-h-[24px]" />
        </div>
        <div className="flex gap-1.5 justify-center items-center self-stretch my-auto">
          <div className="self-stretch my-auto text-xs font-medium leading-snug text-emerald-400">
            {" "}
            {percentage}{" "}
          </div>
          <div className="flex gap-2.5 items-center self-stretch p-0.5 my-auto rounded-3xl bg-green-300 bg-opacity-20 h-[18px] w-[18px]">
            <img
              loading="lazy"
              src={imgSrc}
              alt=""
              className="object-contain w-3.5 aspect-square"
            />
          </div>
        </div>
      </div>
      <div className="flex flex-col mt-2">
        <div className="text-3xl font-semibold leading-snug text-white">
          {" "}
          {amount} token{" "}
        </div>
        <div className="mt-2 text-sm font-medium leading-tight text-indigo-400">
          {" "}
          {label}{" "}
        </div>
      </div>
    </article>
    <img
      loading="lazy"
      src={footerImgSrc}
      alt=""
      className="object-contain shrink-0 self-start mt-4 aspect-square w-[42px]"
    />
  </div>
);

export default TokenCard;
