/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface EventCardProps {
  title: string;
  description: string;
  imageSrc: string;
}

const EventCard: React.FC<EventCardProps> = ({
  title,
  description,
  imageSrc,
}) => {
  return (
    <article className="flex flex-col grow mt-2.5 text-2xl font-bold text-black max-md:mt-10 max-md:max-w-full">
      <img
        loading="lazy"
        src={imageSrc}
        alt={title}
        className="object-contain w-full aspect-[1.85] max-md:max-w-full"
      />
      <div className="px-14 pt-14 pb-5 mt-7 rounded-3xl bg-zinc-300 max-md:px-5 max-md:max-w-full">
        <h2>{title}</h2>
        <p className="text-base font-normal">{description}</p>
      </div>
    </article>
  );
};

export default EventCard;
