/**
 * This code was generated by Builder.io.
 */
import React from "react";
import SearchBar from "../SearchBar/SearchBar";
import EventCard from "./EventCard";

const MainContent: React.FC = () => {
  return (
    <main className="flex flex-col ml-5 w-[78%] max-md:ml-0 max-md:w-full">
      <div className="flex flex-col mt-2.5 w-full max-md:mt-6 max-md:max-w-full">
        <SearchBar />
        <div className="mt-16 ml-4 max-md:mt-10 max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col">
            <div className="flex flex-col w-[63%] max-md:ml-0 max-md:w-full">
              <EventCard
                title="Where Blockchain Developers Meet, Ideas Compete, and Innovation Triumphs"
                description="Join us at Devmatch 2024, a pivotal event hosted by the Asia Pacific University Blockchain & Cryptocurrency Club, where the brightest student minds across Malaysia converge to tackle the future of blockchain technology. From August 16th to 18th, participants will dive into an intense journey of coding, collaborating, and competing, using their skills to solve real-world problems presented by multinational corporations. This hackathon not only aims to deepen participants' understanding of blockchain and cryptocurrencies through interactive workshops and mentorship but also fosters a vibrant community"
                imageSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/efc0762cc1b6d62266dfce43ea7a18ff16a31aeb41d1636aaff55c34ac7ebccc?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
              />
            </div>
            <div className="flex flex-col ml-5 w-[37%] max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/cf91b483c467623b8335827ae67dce074e6635b5e564826069cf97104232f57c?placeholderIfAbsent=true&apiKey=0f10dcf47d4a4bb986b4f458dff7f90a"
                alt="Event illustration"
                className="object-contain w-full aspect-[0.91] max-md:mt-10"
              />
            </div>
          </div>
        </div>
      </div>
    </main>
  );
};

export default MainContent;
